import { palette } from "./palette";

const DARK_COLORS = [
  ["--color-theme", "dark"],
  ["--background-body", palette.darkGrey.darkGrey500],
  ["--background-overlay", palette.black],
  ["--background-ui01", palette.darkGrey.darkGrey300],
  ["--background-ui02", palette.darkGrey.darkGrey200],
  ["--background-ui03", palette.darkGrey.darkGrey200],
  ["--background-ui04", palette.darkGrey.darkGrey100],
  ["--background-ui05", palette.grey.grey500],
  ["--background-error", palette.red.red300],
  ["--background-warning", palette.orange.orange300],
  ["--background-success", palette.green.green300],
  ["--background-info", palette.blue.blue300],
  ["--field-default", palette.darkGrey.darkGrey500],
  ["--field-disabled", palette.grey.grey300],
  ["--text-text01", palette.grey.grey400],
  ["--text-text02", palette.grey.grey700],
  ["--text-text03", palette.grey.grey800],
  ["--text-text04", palette.darkGrey.darkGrey700],
  ["--text-error", palette.red.red300],
  ["--text-warning", palette.orange.orange800],
  ["--text-success", palette.lightGreen.lightGreen400],
  ["--text-info", palette.blue.blue700],
  ["--border-border01", palette.darkGrey.darkGrey100],
  ["--border-border02", palette.grey.grey700],
  ["--border-input", palette.darkGrey.darkGrey500],
  ["--border-focus", palette.grey.grey800],
  ["--border-error", palette.red.red700],
  ["--interactive-primary", palette.grey.grey500],
  ["--interactive-primaryHover", palette.grey.grey600],
  ["--interactive-primaryActive", palette.grey.grey700],
  ["--interactive-secondary", palette.darkGrey.darkGrey400],
  ["--interactive-secondaryHover", palette.darkGrey.darkGrey500],
  ["--interactive-secondaryActive", palette.darkGrey.darkGrey600],
  ["--interactive-link", palette.deepBlue.deepBlue200],
  ["--interactive-linkInverse", palette.deepBlue.deepBlue200],
  ["--interactive-error", palette.red.red400],
  ["--interactive-errorHover", palette.red.red500],
  ["--interactive-errorActive", palette.red.red600],
  ["--interactive-success", palette.green.green400],
  ["--interactive-successHover", palette.green.green500],
  ["--interactive-successActive", palette.green.green600],
  ["--interactive-info", palette.blue.blue400],
  ["--interactive-infoHover", palette.blue.blue500],
  ["--interactive-infoActive", palette.blue.blue600],
  ["--interactive-disabled", palette.darkGrey.darkGrey200],
  ["--support-red", palette.red.red400],
  ["--support-redInverse", palette.darkGrey.darkGrey100],
  ["--support-pink", palette.pink.pink400],
  ["--support-purple", palette.purple.purple400],
  ["--support-indigo", palette.indigo.indigo300],
  ["--support-blue", palette.blue.blue400],
  ["--support-blueInverse", palette.darkGrey.darkGrey100],
  ["--support-grey", palette.grey.grey800],
  ["--support-greyInverse", palette.grey.grey300],
  ["--support-cyan", palette.cyan.cyan400],
  ["--support-teal", palette.teal.teal400],
  ["--support-green", palette.lightGreen.lightGreen400],
  ["--support-greenInverse", palette.darkGrey.darkGrey100],
  ["--support-lightGreen", palette.lightGreen.lightGreen400],
  ["--support-yellow", palette.yellow.yellow400],
  ["--support-orange", palette.orange.orange400],
  ["--support-orangeInverse", palette.darkGrey.darkGrey100],
];

export default DARK_COLORS;
