name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - run: echo "registry=https://registry.npmjs.org/" > .npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
      - run: npm ci
      - run: npm audit signatures
      - run: npm run build
      - run: cat .npmrc
      - run: npm publish --access public
